
services:
 
  dispatcher-service:
    build: ./dispatcher-service
    container_name: dispatcher
    ports:
      - "8000:8000"
    depends_on:
      - redis-dispatcher
    networks:
      - yazlab_network

  
  auth-service:
    build: ./auth-service
    container_name: auth-service
    expose:
      - "8003"
    depends_on:
      - redis-auth
    networks:
      - yazlab_network

  
  user-service:
    build: ./user-service
    container_name: user-service
    expose:
      - "8001" 
    depends_on:
      - mongo-user
    networks:
      - yazlab_network

 
  post-service:
    build: ./post-service
    container_name: post-service
    expose:
      - "8002"
    depends_on:
      - mongo-post
    networks:
      - yazlab_network

  
  redis-dispatcher:
    image: redis:alpine
    container_name: redis-dispatcher
    networks:
      - yazlab_network

  redis-auth:
    image: redis:alpine
    container_name: redis-auth
    networks:
      - yazlab_network

  mongo-user:
    image: mongo:latest
    container_name: mongo-user
    networks:
      - yazlab_network

  mongo-post:
    image: mongo:latest
    container_name: mongo-post
    networks:
      - yazlab_network

networks:
  yazlab_network:
    driver: bridge